version: '3'
services:
    web-auth:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/auth.pantheonbots.trade.conf:/etc/nginx/conf.d/default.conf"
            #- "./etc/ssl:/etc/ssl"
            - "./auth:/var/www/html"
        ports:
            - "8000:80"
            - "3000:443"
        #environment:
        #    - NGINX_HOST=${NGINX_HOST}
        #command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysql
    php:
        image: php:7.3-fpm-alpine
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./auth:/var/www/html"
    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"